[meta]
name = "Ultimate Medals++"
author = "Catalistique"
category = "Race"
version = "1.1.0"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "WarriorMedals" ]